global:
  smtp_smarthost: 'smtp.example.com:465'
  smtp_from: 'my-alerter@example.com'
  smtp_auth_username: 'username@example.com'
  smtp_auth_password: 'my_crap_password'
  smtp_require_tls: true

templates:
- '*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 15m
  receiver: email_env

inhibit_rules:
- source_matchers: [ severity="critical" ]
  target_matchers: [ severity="warning" ]
  equal: [ alertname ]

receivers:
- name: 'email_env'
  email_configs:
    - send_resolved: true
      to: 'recipient@example.com'
      headers:
        subject: '{{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'
